### ISSUE TITLE
Bridge.groups(): List<dynamic> is not a subtype of Map<String, dynamic>

### ISSUE THREAD

**Issue by lukepighetti** [Jairzinno/hue_dart#8]
The `Bridge.groups` method fails with `type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast`

```dart
import 'package:http/http.dart';
import 'package:hue_dart/hue_dart.dart';

void main(List<String> arguments) async {
  final client = Client();
  final discovery = BridgeDiscovery(client);

  final discoverResults = await discovery.automatic();
  final discoveryResult = discoverResults.first;

  final bridge = Bridge(client, discoveryResult.ipAddress);

  final groups = await bridge.groups();
}
```

```yaml
name: dart_hue_desktop
description: Spike a desktop hue controller.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  hue_dart: ^0.3.0

dev_dependencies:
  pedantic: ^1.9.0

```

```
% dart --version
Dart SDK version: 2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "macos_x64"
```

```
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      BridgeClient.get
package:hue_dart/…/core/bridge_client.dart:21
<asynchronous suspension>
#1      GroupApi.all
package:hue_dart/…/group/group_api.dart:20
<asynchronous suspension>
```
